export const Questions = [
  

  {
    prompt: "What is the capital of France?",
    optionA: "Tokyo",
    optionB: "Paris",
    optionC: "Rome",
    optionD: "Delhi",
    answer: "B",
  },
  {
    prompt: "Which planet is known as the Red Planet?",
    optionA: "Mars",
    optionB: "Jupiter",
    optionC: "Venus",
    optionD: "Saturn",
    answer: "A",
  },
  {
    prompt: "What is the largest mammal?",
    optionA: "Elephant",
    optionB: "Giraffe",
    optionC: "Blue Whale",
    optionD: "Lion",
    answer: "C",
  },
  {
    prompt: "What is the currency of Japan?",
    optionA: "Yen",
    optionB: "Dollar",
    optionC: "Euro",
    optionD: "Pound",
    answer: "A",
  },
  {
    prompt: "Which famous scientist developed the theory of relativity?",
    optionA: "Isaac Newton",
    optionB: "Galileo Galilei",
    optionC: "Albert Einstein",
    optionD: "Nikola Tesla",
    answer: "C",
  },
  {
    prompt: "What is the largest ocean on Earth?",
    optionA: "Atlantic Ocean",
    optionB: "Indian Ocean",
    optionC: "Arctic Ocean",
    optionD: "Pacific Ocean",
    answer: "D",
  },
  {
    prompt: "Which novel is authored by Jane Austen?",
    optionA: "Wuthering Heights",
    optionB: "Pride and Prejudice",
    optionC: "Great Expectations",
    optionD: "1984",
    answer: "B",
  },
  {
    prompt: "Which gas do plants use for photosynthesis?",
    optionA: "Oxygen",
    optionB: "Carbon Dioxide",
    optionC: "Nitrogen",
    optionD: "Hydrogen",
    answer: "B",
  },
  {
    prompt: "What is the chemical symbol for gold?",
    optionA: "Ag",
    optionB: "Au",
    optionC: "Fe",
    optionD: "Hg",
    answer: "B",
  },
  {
    prompt: "Which famous artist painted the Mona Lisa?",
    optionA: "Vincent van Gogh",
    optionB: "Pablo Picasso",
    optionC: "Leonardo da Vinci",
    optionD: "Michelangelo",
    answer: "C",
  },
];
